{
  "openapi": "3.0.0",
  "info": {
    "description": "This is Miare Third-Party API, designed to enable registered Miare users to integrate our delivery services into their applications.",
    "version": "2.1.0",
    "title": "Miare API",
    "contact": {
      "email": "tech@miare.ir",
      "name": "Miare's Tech Team",
      "url": "https://mia.re"
    }
  },
  "tags": [
    {
      "name": "delivery",
      "description": "Delivery related services"
    },
    {
      "name": "events",
      "description": "Realtime webhook events"
    },
    {
      "name": "accounting"
    },
    {
      "name": "area"
    }
  ],
  "servers": [
    {
      "url": "https://ws.mia.re",
      "description": "Production server of trip management."
    },
    {
      "url": "https://ws.staging.mia.re",
      "description": "Staging server of trip management."
    },
    {
      "url": "https://www.mia.re/api/accounting",
      "description": "Production server of accounting"
    },
    {
      "url": "https://www.staging.mia.re/api/accounting",
      "description": "Staging server of accounting"
    }
  ],
  "components": {
    "securitySchemes": {
      "auth": {
        "name": "Authorization",
        "type": "apiKey",
        "in": "header",
        "description": "You should put the private token that has been sent to you as the `value` field of `Authorization` header, prependded by `Token: <YOUR PRIVATE TOKEN>`. For example: `Token: qwertyasdfqwersadfasdf`"
      }
    },
    "schemas": {
      "Trip": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "description": "Unique ID of this trip",
            "example": "40626ed5-9260-4a55-af04-ef9705a41b90"
          },
          "area": {
            "$ref": "#/components/schemas/Area"
          },
          "state": {
            "type": "string",
            "description": "Current state of this trip",
            "example": "pickup",
            "enum": [
              "assign_queue",
              "pickup",
              "dropoff",
              "delivered",
              "canceled_by_miare",
              "canceled_by_client"
            ]
          },
          "pickup": {
            "$ref": "#/components/schemas/Pickup"
          },
          "courses": {
            "type": "array",
            "description": "All of the different courses at which parts of this trip should be dropped off",
            "xml": {
              "name": "course",
              "wrapped": true
            },
            "items": {
              "$ref": "#/components/schemas/Course"
            }
          },
          "created_at": {
            "type": "string",
            "format": "date-time",
            "description": "The exact moment at which this trip is created for the first time",
            "example": "2019-04-12T13:58:42+0000"
          },
          "assigned_at": {
            "type": "string",
            "format": "date-time",
            "description": "The time this trip was assigned to its current courier",
            "example": "2019-04-12T13:59:59+0000"
          },
          "picked_up_at": {
            "type": "string",
            "format": "date-time",
            "description": "The time at which the courier picked up the items from pickup location",
            "example": "2019-04-12T14:10:42+0000"
          },
          "courier": {
            "$ref": "#/components/schemas/Courier"
          },
          "test_mode": {
            "type": "boolean",
            "description": "Whether or not this trip was created in test mode",
            "example": false
          }
        },
        "xml": {
          "name": "Trip"
        },
        "x-examples": {
          "Example": {
            "id": "40626ed5-9260-4a55-af04-ef9705a41b90",
            "area": {
              "id": "59",
              "name": "فردوس شرق"
            },
            "state": "assign_queue",
            "pickup": {
              "name": "رستوران بزرگمهر",
              "phone_number": "0212345678",
              "address": "تهران، صادقیه، بلوار آیت الله کاشانی",
              "image": "https://example.com/restaurants/bm_logo.png",
              "location": {
                "latitude": 35.737004,
                "longitude": 51.413569
              },
              "deadline": "2019-04-12T14:12:00+0000"
            },
            "courses": [
              {
                "id": "40626ed5-9260-4a55-af04-ef9705a41b90",
                "bill_number": "DEL-119",
                "name": "علی علوی",
                "phone_number": "09123456789",
                "address": "هران، خیابان استاد معین، پلاک ۱۲",
                "location": {
                  "latitude": 35.737004,
                  "longitude": 51.413569
                },
                "manifest_items": [
                  {
                    "name": "پیتزا پپرونی خانواده",
                    "quantity": 2
                  }
                ],
                "tracking_url": "https://mia.re/t/73c939d1/",
                "dropped_off_at": "2019-04-12T14:06:42+0000"
              }
            ],
            "created_at": "2019-04-12T13:58:42+0000",
            "assigned_at": "2019-04-12T13:59:59+0000",
            "picked_up_at": "2019-04-12T14:10:42+0000",
            "courier": {
              "name": "علی لطفی",
              "image": "https://files.miare.ir/avatars/gheuIej.jpg",
              "location_updated_at": "2019-08-24T14:15:22Z",
              "location": {
                "latitude": 35.737004,
                "longitude": 51.413569
              }
            },
            "test_mode": false
          }
        }
      },
      "Pickup": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The human readable name of the pickup",
            "example": "رستوران بزرگمهر"
          },
          "phone_number": {
            "type": "string",
            "description": "The phone number associated with the source which will be used by courier and support staffs in order to contact to pickup if necessary",
            "example": "0212345678"
          },
          "address": {
            "type": "string",
            "description": "The human readable address of the source, preferably down to every necessary detail for a human to find the source quickly",
            "example": "تهران، صادقیه، بلوار آیت الله کاشانی"
          },
          "image": {
            "type": "string",
            "format": "uri",
            "description": "A valid URL which points to an image file which should be the logo of the pickup. This image will be used in both support panel, and courier’s application, so make sure that the URL is both reachable and is configured to allow CORS requests",
            "example": "https://example.com/restaurants/bm_logo.png"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "deadline": {
            "type": "string",
            "format": "date-time",
            "description": "The time that you expect the courier to arrive at the pickup, so optimally it should be the time package content is ready and packaged",
            "example": "2019-04-12T14:12:00+0000"
          }
        },
        "xml": {
          "name": "Pickup"
        }
      },
      "Course": {
        "type": "object",
        "required": [
          "bill_number",
          "name",
          "phone_number",
          "address"
        ],
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "description": "The unique identifier of this course",
            "example": "40626ed5-9260-4a55-af04-ef9705a41b90"
          },
          "trip_id": {
            "type": "string",
            "format": "uuid",
            "description": "The unique identifier of the trip that the course belongs to",
            "example": "40626ed5-9260-4a55-af04-ef9705a41b90"
          },
          "bill_number": {
            "type": "string",
            "description": "An string field left for you to store sort of a human readable bill number in it which will be used as a reference point among our support team, you and the pickup staffs",
            "example": "DEL-119"
          },
          "name": {
            "type": "string",
            "description": "Name of the dropp-off",
            "example": "علی علوی"
          },
          "phone_number": {
            "type": "string",
            "description": "The phone number associated with the drop-off which will be used by courier and support staffs in order to contact to them if necessary",
            "example": "09123456789"
          },
          "address": {
            "type": "string",
            "description": "The human readable drop-off address, preferably down to every necessary detail for a human to find it quickly",
            "example": "هران، خیابان استاد معین، پلاک ۱۲"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "manifest_items": {
            "type": "array",
            "xml": {
              "name": "manifest_item",
              "wrapped": true
            },
            "description": "The contents of the package to be delivered to the drop-off",
            "items": {
              "$ref": "#/components/schemas/ManifestItem"
            }
          },
          "tracking_url": {
            "type": "string",
            "format": "uri",
            "description": "The URL of Miare Tracking webpage which can be given to user so he/she can follow the courier in real-time",
            "example": "https://mia.re/t/73c939d1/"
          },
          "dropped_off_at": {
            "type": "string",
            "format": "date-time",
            "description": "The time this course was dropped off by courier",
            "example": "2019-04-12T14:06:42+0000"
          }
        },
        "xml": {
          "name": "Course"
        }
      },
      "Location": {
        "type": "object",
        "properties": {
          "latitude": {
            "type": "number",
            "format": "double",
            "example": 35.737004
          },
          "longitude": {
            "type": "number",
            "format": "double",
            "example": 51.413569
          }
        },
        "xml": {
          "name": "Location"
        }
      },
      "ManifestItem": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Human readable name of the content which will be verified by courier",
            "example": "پیتزا پپرونی خانواده"
          },
          "quantity": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "description": "The quanitiy of the given item",
            "example": 2
          }
        },
        "xml": {
          "name": "ManifestItem"
        }
      },
      "Area": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique identifier of area",
            "example": "59"
          },
          "name": {
            "type": "string",
            "description": "Textual name of the area",
            "example": "فردوس شرق"
          }
        },
        "xml": {
          "name": "Area"
        }
      },
      "Courier": {
        "type": "object",
        "xml": {
          "name": "Courier"
        },
        "x-examples": {
          "Example": {
            "name": "علی لطفی",
            "image": "https://files.miare.ir/avatars/gheuIej.jpg",
            "location_updated_at": "2019-08-24T14:15:22Z",
            "location": {
              "latitude": 35.737004,
              "longitude": 51.413569
            }
          }
        },
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the driver",
            "example": "علی لطفی"
          },
          "image": {
            "type": "string",
            "format": "uri",
            "description": "A photo of the courier",
            "example": "https://files.miare.ir/avatars/gheuIej.jpg"
          },
          "location_updated_at": {
            "description": "The datetime that the latest location of the courier is stored",
            "oneOf": [
              {
                "format": "date-time",
                "example": "2019-08-24T14:15:22Z",
                "description": "The datetime that the latest location of the courier is stored",
                "behavior": "Read Only"
              }
            ],
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "phone_number": {
            "type": "string",
            "example": "09123456789"
          }
        }
      },
      "Event": {
        "xml": {
          "name": "Event"
        },
        "oneOf": [
          {
            "properties": {
              "event": {
                "type": "string",
                "description": "The event being reported",
                "enum": [
                  "course_added__course"
                ]
              },
              "course": {
                "$ref": "#/components/schemas/Course"
              }
            }
          },
          {
            "properties": {
              "event": {
                "type": "string",
                "description": "The event being reported",
                "enum": [
                  "added",
                  "assigned",
                  "course_added",
                  "course_deleted",
                  "picked_up",
                  "course_dropped_off",
                  "delivered",
                  "canceled_by_client",
                  "canceled_by_miare"
                ]
              },
              "trip": {
                "$ref": "#/components/schemas/Trip"
              }
            }
          }
        ],
        "type": "object"
      },
      "Error": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": "Constant error code",
            "example": "trip_not_found"
          },
          "detail": {
            "type": "string",
            "description": "Human readable explanation of the error",
            "example": "Could not find trip with id \"wrong_id\""
          }
        }
      },
      "AreaInfo": {
        "description": "This model returns data about each area defined in Miare, and data about your ongoing trips in them.\n\nThese data include:\n\n - `id`: The id of this area\n - `name`: The human readable name of this area\n - `polygon`: The coordinates of this area, in GeoJSON format\n - `max_ongoing_trips`: The maximum number of concurrent trips you can have in this area right now, based on your subscription.\n - `ongoing_trips`: Number of your ongonig trips in this area at the moment.",
        "type": "object",
        "x-examples": {
          "Example": {
            "id": 5,
            "max_ongoing_trips": 7,
            "name": "قلهک",
            "ongoing_trips": 3,
            "polygon": {
              "type": "Polygon",
              "coordinates": [
                [
                  [
                    51.4549231005859,
                    35.6696883542151
                  ],
                  [
                    51.4571858393479,
                    35.6945690813052
                  ],
                  [
                    51.4497587368011,
                    35.6834941116055
                  ],
                  [
                    51.4549231005859,
                    35.6696883542151
                  ]
                ]
              ]
            }
          }
        },
        "properties": {
          "id": {
            "type": "number",
            "minimum": 1,
            "example": 5
          },
          "max_ongoing_trips": {
            "type": "number",
            "description": "The maximum number of concurrent trips that you can have in this area at the moment, based on your subscription.",
            "minimum": 0,
            "example": 7
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "example": "قلهک"
          },
          "ongoing_trips": {
            "type": "number",
            "minimum": 0,
            "example": 3,
            "description": "Count of your trips that are ongoing concurrently right now."
          },
          "polygon": {
            "type": "object",
            "description": "Polygon of area coordinates, in GeoJSON format.",
            "required": [
              "type",
              "coordinates"
            ],
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1,
                "enum": [
                  "Polygon"
                ],
                "example": "Polygon"
              },
              "coordinates": {
                "type": "array",
                "items": {
                  "type": "array",
                  "items": {
                    "type": "array",
                    "minItems": 2,
                    "maxItems": 2,
                    "items": {
                      "type": "number",
                      "example": 35.532345
                    }
                  }
                }
              }
            }
          }
        },
        "required": [
          "id",
          "max_ongoing_trips",
          "name",
          "ongoing_trips",
          "polygon"
        ]
      }
    },
    "requestBodies": {
      "EventBody": {
        "description": "Event happened for a trip",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Event"
            }
          }
        }
      }
    }
  },
  "paths": {
    "/trip-management/third-party-api/v2/trips": {
      "post": {
        "tags": [
          "delivery"
        ],
        "summary": "Creates a new trip and puts it in the assign queue",
        "description": "Note that trip creation will fail if you don't have enough concurrency limit in the area of the pickup location of the given trip.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "pickup": {
                    "$ref": "#/components/schemas/Pickup"
                  },
                  "courses": {
                    "type": "array",
                    "xml": {
                      "name": "course",
                      "wrapped": true
                    },
                    "items": {
                      "$ref": "#/components/schemas/Course"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully created trip",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Trip"
                }
              }
            }
          },
          "400": {
            "description": "A validation error indicating failure in trip creation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "enum": [
                        "parse_error",
                        "invalid_request_body",
                        "concurrency_limit",
                        "service_level_order"
                      ]
                    },
                    "details": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error"
          }
        },
        "operationId": "posttrip-management-third-party-api-v2-trips"
      },
      "parameters": [],
      "get": {
        "summary": "Returns list of your trips",
        "operationId": "gettrip-management-third-party-api-v2-trips",
        "responses": {
          "200": {
            "description": "Returns list of trips, put in a pagination format.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Trip"
                      }
                    },
                    "next": {
                      "type": "string",
                      "description": "URL to fetch next page of this data. Could be an empty string if there's no more pages available.",
                      "example": " https://ws.staging.mia.re/trip-management/third-party-api/v2/trips/?offset=100",
                      "minLength": 0
                    },
                    "previous": {
                      "type": "string",
                      "description": "URL to fetch previous page of this data. Could be an empty string if this is the first page.",
                      "minLength": 0,
                      "example": " https://ws.staging.mia.re/trip-management/third-party-api/v2/trips/?offset=100"
                    },
                    "total_count": {
                      "type": "integer",
                      "description": "Count of all trips that match the filtering you've applied. Please Note that if `total_count` is more than `limit`, not all of these trips would be returned in this response.",
                      "minimum": 0,
                      "example": 742
                    }
                  },
                  "required": [
                    "data",
                    "next",
                    "previous",
                    "total_count"
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "data": [
                        {
                          "id": "40626ed5-9260-4a55-af04-ef9705a41b90",
                          "area": {
                            "id": "59",
                            "name": "فردوس شرق"
                          },
                          "state": "pickup",
                          "pickup": {
                            "name": "رستوران بزرگمهر",
                            "phone_number": "0212345678",
                            "address": "تهران، صادقیه، بلوار آیت الله کاشانی",
                            "image": "https://example.com/restaurants/bm_logo.png",
                            "location": {
                              "latitude": 35.737004,
                              "longitude": 51.413569
                            },
                            "deadline": "2019-04-12T14:12:00+0000"
                          },
                          "courses": [
                            {
                              "id": "40626ed5-9260-4a55-af04-ef9705a41b90",
                              "bill_number": "DEL-119",
                              "name": "علی علوی",
                              "phone_number": "09123456789",
                              "address": "هران، خیابان استاد معین، پلاک ۱۲",
                              "location": {
                                "latitude": 35.737004,
                                "longitude": 51.413569
                              },
                              "manifest_items": [
                                {
                                  "name": "پیتزا پپرونی خانواده",
                                  "quantity": 2
                                }
                              ],
                              "tracking_url": "https://mia.re/t/73c939d1/",
                              "dropped_off_at": "2019-04-12T14:06:42+0000"
                            }
                          ],
                          "created_at": "2019-04-12T13:58:42+0000",
                          "assigned_at": "2019-04-12T13:59:59+0000",
                          "picked_up_at": "2019-04-12T14:10:42+0000",
                          "courier": {
                            "name": "علی لطفی",
                            "phone_number": "9123456789",
                            "image": "https://files.miare.ir/avatars/gheuIej.jpg",
                            "location_updated_at": "2019-04-12T14:10:42+0000",
                            "location": {
                              "latitude": 35.737004,
                              "longitude": 51.413569
                            }
                          },
                          "test_mode": false
                        }
                      ],
                      "next": " https://ws.staging.mia.re/trip-management/third-party-api/v2/trips/?offset=100",
                      "previous": " https://ws.staging.mia.re/trip-management/third-party-api/v2/trips/?offset=100",
                      "total_count": 742
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Returns list of all your trips, using an Offset-Limit schema for pagination.\n",
        "parameters": [
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "area_id",
            "description": "Filter trips only for this specific area. List of all areas could be fetched using [this endpoint](miare-v2.1.0.json/paths/~1area~1third-party-api~1v2~1areas~1)"
          },
          {
            "schema": {
              "type": "string",
              "enum": [
                "assign_queue",
                "pickup",
                "dropoff",
                "delivered",
                "canceled_by_client",
                "canceled_by_miare"
              ]
            },
            "in": "query",
            "name": "state",
            "description": "Returns trips that currently have this state."
          },
          {
            "schema": {
              "type": "string",
              "example": "2020-01-01T01:02:03+0330",
              "format": "date-time"
            },
            "in": "query",
            "name": "from_datetime",
            "description": "Returns trips requested after this datetime"
          },
          {
            "schema": {
              "type": "string",
              "example": "2020-01-01T01:02:03+0330",
              "format": "date-time"
            },
            "in": "query",
            "name": "to_datetime",
            "description": "Returns trips requested before this datetime"
          },
          {
            "schema": {
              "type": "integer",
              "minimum": 0
            },
            "in": "query",
            "name": "offset",
            "description": "Filters trips to start at the offset specified (used for pagination)"
          },
          {
            "schema": {
              "type": "integer",
              "default": "100",
              "minimum": 0,
              "maximum": 100
            },
            "in": "query",
            "name": "limit",
            "description": "Limits count of trips returned in this response (used for pagination)"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "bill_number",
            "description": "Returns trips with courses with the same bill_number as query values"
          }
        ],
        "tags": [
          "delivery"
        ]
      }
    },
    "/trip-management/third-party-api/v2/trips/{trip_id}/cancel": {
      "post": {
        "tags": [
          "delivery"
        ],
        "summary": "Cancels the given trip",
        "description": "Note that a trip CANNOT be cancelled when it has passed 30 seconds since we’ve assigned it to a courier or the courier has already arrived at the source. In special cases which you still need to cancel the trip, please contact our support.",
        "parameters": [
          {
            "name": "trip_id",
            "in": "path",
            "required": true,
            "description": "The ID of the trip to be cancelled",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully cancelled trip",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Trip"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": "40626ed5-9260-4a55-af04-ef9705a41b90",
                      "area": {
                        "id": "59",
                        "name": "فردوس شرق"
                      },
                      "state": "canceled_by_client",
                      "pickup": {
                        "name": "رستوران بزرگمهر",
                        "phone_number": "0212345678",
                        "address": "تهران، صادقیه، بلوار آیت الله کاشانی",
                        "image": "https://example.com/restaurants/bm_logo.png",
                        "location": {
                          "latitude": 35.737004,
                          "longitude": 51.413569
                        },
                        "deadline": "2019-04-12T14:12:00+0000"
                      },
                      "courses": [
                        {
                          "id": "40626ed5-9260-4a55-af04-ef9705a41b90",
                          "bill_number": "DEL-119",
                          "name": "علی علوی",
                          "phone_number": "09123456789",
                          "address": "هران، خیابان استاد معین، پلاک ۱۲",
                          "location": {
                            "latitude": 35.737004,
                            "longitude": 51.413569
                          },
                          "manifest_items": [
                            {
                              "name": "پیتزا پپرونی خانواده",
                              "quantity": 2
                            }
                          ],
                          "tracking_url": "https://mia.re/t/73c939d1/",
                          "dropped_off_at": "2019-04-12T14:06:42+0000"
                        }
                      ],
                      "created_at": "2019-04-12T13:58:42+0000",
                      "assigned_at": "2019-04-12T13:59:59+0000",
                      "picked_up_at": "2019-04-12T14:10:42+0000",
                      "courier": {
                        "name": "علی لطفی",
                        "phone_number": "09123456789",
                        "image": "https://files.miare.ir/avatars/gheuIej.jpg",
                        "location_updated_at": "2019-08-24T14:15:22Z",
                        "location": {
                          "latitude": 35.737004,
                          "longitude": 51.413569
                        }
                      },
                      "test_mode": false
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "A validation error indicating failure in trip cancellation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "enum": [
                        "parse_error",
                        "invalid_request_body",
                        "canceling_ended_trip",
                        "invalid_state_change",
                        "canceling_arrived_trip",
                        "canceling_after_deadline"
                      ]
                    },
                    "details": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error"
          }
        },
        "operationId": "cancel-trip-management-third-party-api-v2-trips-trip_id-cancel"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "trip_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/trip-management/third-party-api/v2/trips/{trip_id}/courses": {
      "patch": {
        "tags": [
          "delivery"
        ],
        "summary": "Add a course to the given trip",
        "description": "Note that you cannot add a course to an already picked up trip.",
        "parameters": [
          {
            "name": "trip_id",
            "in": "path",
            "required": true,
            "description": "The ID of the trip to add a course to",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "bill_number",
                  "name",
                  "phone_number",
                  "address"
                ],
                "properties": {
                  "bill_number": {
                    "type": "string",
                    "description": "An string field left for you to store sort of a human readable bill number in it which will be used as a reference point among our support team, you and the pickup staffs",
                    "example": "DEL-119"
                  },
                  "name": {
                    "type": "string",
                    "description": "Name of the dropp-off",
                    "example": "علی علوی"
                  },
                  "phone_number": {
                    "type": "string",
                    "description": "The phone number associated with the drop-off which will be used by courier and support staffs in order to contact to them if necessary",
                    "example": "09123456789"
                  },
                  "address": {
                    "type": "string",
                    "description": "The human readable drop-off address, preferably down to every necessary detail for a human to find it quickly",
                    "example": "هران، خیابان استاد معین، پلاک ۱۲"
                  },
                  "location": {
                    "$ref": "#/components/schemas/Location"
                  },
                  "manifest_items": {
                    "type": "array",
                    "xml": {
                      "name": "manifest_item",
                      "wrapped": true
                    },
                    "description": "The contents of the package to be delivered to the drop-off",
                    "items": {
                      "$ref": "#/components/schemas/ManifestItem"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully added a course to the trip",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Trip"
                }
              }
            }
          },
          "400": {
            "description": "A validation error indicating failure in adding the course",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "enum": [
                        "parse_error",
                        "invalid_request_body"
                      ]
                    },
                    "details": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error"
          }
        },
        "operationId": "patch-trip-management-third-party-api-v2-trips-trip_id-courses"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "trip_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/trip-management/third-party-api/v2/courses/{course_id}": {
      "delete": {
        "tags": [
          "delivery"
        ],
        "summary": "Removes the given course from its trip",
        "description": "Note you cannot remove an alreay picked up course.",
        "parameters": [
          {
            "name": "course_id",
            "in": "path",
            "required": true,
            "description": "The ID of the course to be removed",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully removed the course",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Trip"
                }
              }
            }
          },
          "400": {
            "description": "A validation error indicating failure in coures removal",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "enum": [
                        "parse_error",
                        "invalid_request_body"
                      ]
                    },
                    "details": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error"
          }
        },
        "operationId": "delete-trip-management-third-party-api-v2-courses-course_id"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "course_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/subscribe": {
      "post": {
        "tags": [
          "events"
        ],
        "summary": "Callbacks made by our server",
        "description": "There are different callbacks which will be made in different lifetime stages of a trip. All of them will be sent to the webhook address you’ve provided to the technical team. All of them will contain credential token as a HTTP header as described in the Authentication section and a `X-Miare-API-Version` header indicating the version of API in which the Event’s format will be.",
        "responses": {
          "200": {
            "description": "This is just a placeholder for events"
          }
        },
        "callbacks": {
          "event": {
            "your_webhook_url": {
              "post": {
                "requestBody": {
                  "$ref": "#/components/requestBodies/EventBody"
                },
                "responses": {
                  "200": {
                    "description": "OK"
                  }
                }
              }
            }
          }
        },
        "operationId": "subscribe"
      }
    },
    "/accounting/estimate/price": {
      "get": {
        "summary": "Price Estimation",
        "tags": [
          "accounting"
        ],
        "responses": {
          "200": {
            "description": "Returns price of such a trip.",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "price": {
                      "type": "number",
                      "example": 20000,
                      "description": "Price a trip with this source & destination, in IRT"
                    },
                    "status": {
                      "type": "string",
                      "example": "ok",
                      "description": "status"
                    }
                  },
                  "required": [
                    "price",
                    "status"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Error on when a required parameter isn't provided",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "minLength": 1,
                      "enum": [
                        "invalid"
                      ],
                      "description": "Error code"
                    },
                    "detail": {
                      "type": "string",
                      "minLength": 1,
                      "description": "Detail of this error"
                    },
                    "metadata": {
                      "type": "object",
                      "required": [
                        "field_name",
                        "required_data_type"
                      ],
                      "properties": {
                        "field_name": {
                          "type": "string",
                          "minLength": 1,
                          "description": "Name of the field that is required & isn't provided",
                          "enum": [
                            "source",
                            "destination"
                          ]
                        },
                        "required_data_type": {
                          "type": "string",
                          "minLength": 1
                        }
                      }
                    }
                  },
                  "required": [
                    "code",
                    "detail",
                    "metadata"
                  ]
                }
              }
            }
          }
        },
        "operationId": "get-accounting-estimate-price",
        "description": "This endpoint would return price of a particular trip, based on source & destination that you provide it with.",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "35.7325,55.6453"
            },
            "in": "query",
            "name": "source",
            "description": "Coordinates of source of trip, separated by `,` and no spaces.",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "35.7325,55.6453"
            },
            "in": "query",
            "name": "destination",
            "description": "Coordinates of destination of trip, separated by `,` and no spaces.",
            "required": true
          }
        ],
        "security": [
          {
            "auth": []
          }
        ]
      },
      "parameters": []
    },
    "/area/third-party-api/v2/areas": {
      "get": {
        "summary": "Returns list of all areas & count of your trips in them",
        "tags": [
          "area"
        ],
        "responses": {
          "200": {
            "description": "Returns data of all areas, which is an array of [`AreaInfo`](miare-v2.1.0.json/components/schemas/AreaInfo) objects.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/AreaInfo"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "id": 5,
                        "max_ongoing_trips": 7,
                        "name": "قلهک",
                        "ongoing_trips": 3,
                        "polygon": {
                          "type": "Polygon",
                          "coordinates": [
                            [
                              [
                                35.532345,
                                35.532345
                              ]
                            ]
                          ]
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-area-third-party-api-v2-areas",
        "description": "Using this endpoint you can get a list of all areas defined in Miare, plus information about you trips in these areas."
      }
    },
    "/trip-management/third-party-api/v2/trips/{trip_id}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "trip_id",
          "in": "path",
          "required": true,
          "description": "id of the trip you want"
        }
      ],
      "get": {
        "summary": "Returns a particular trip",
        "tags": [
          "delivery"
        ],
        "operationId": "get-trip-management-third-party-api-v2-trips-trip_id",
        "description": "Get info of a particular trip.",
        "parameters": [],
        "x-internal": false,
        "responses": {
          "200": {
            "description": "Returns the trip data, which uses schema of [Trip](miare-v2.1.0.json/components/schemas/Trip) object.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Trip"
                },
                "examples": {
                  "example-13": {
                    "value": {
                      "id": "40626ed5-9260-4a55-af04-ef9705a41b90",
                      "area": {
                        "id": "59",
                        "name": "فردوس شرق"
                      },
                      "state": "pickup",
                      "pickup": {
                        "name": "رستوران بزرگمهر",
                        "phone_number": "0212345678",
                        "address": "تهران، صادقیه، بلوار آیت الله کاشانی",
                        "image": "https://example.com/restaurants/bm_logo.png",
                        "location": {
                          "latitude": 35.737004,
                          "longitude": 51.413569
                        },
                        "deadline": "2019-04-12T14:12:00+0000"
                      },
                      "courses": [
                        {
                          "id": "40626ed5-9260-4a55-af04-ef9705a41b90",
                          "bill_number": "DEL-119",
                          "name": "علی علوی",
                          "phone_number": "09123456789",
                          "address": "هران، خیابان استاد معین، پلاک ۱۲",
                          "location": {
                            "latitude": 35.737004,
                            "longitude": 51.413569
                          },
                          "manifest_items": [
                            {
                              "name": "پیتزا پپرونی خانواده",
                              "quantity": 2
                            }
                          ],
                          "tracking_url": "https://mia.re/t/73c939d1/",
                          "dropped_off_at": "2019-04-12T14:06:42+0000"
                        }
                      ],
                      "created_at": "2019-04-12T13:58:42+0000",
                      "assigned_at": "2019-04-12T13:59:59+0000",
                      "picked_up_at": "2019-04-12T14:10:42+0000",
                      "courier": {
                        "name": "علی لطفی",
                        "phone_number": "09123456789",
                        "image": "https://files.miare.ir/avatars/gheuIej.jpg",
                        "location_updated_at": "2019-08-24T14:15:22Z",
                        "location": {
                          "latitude": 35.737004,
                          "longitude": 51.413569
                        }
                      },
                      "test_mode": false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "auth": []
    }
  ]
}
